# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\"#\n\rLookupRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\"D\n\x0eLookupResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x32K\n\x0cStockMessage\x12;\n\x06Lookup\x12\x17.messages.LookupRequest\x1a\x18.messages.LookupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=28
  _globals['_LOOKUPREQUEST']._serialized_end=63
  _globals['_LOOKUPRESPONSE']._serialized_start=65
  _globals['_LOOKUPRESPONSE']._serialized_end=133
  _globals['_STOCKMESSAGE']._serialized_start=135
  _globals['_STOCKMESSAGE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
